server:
  port: 8081
spring:
  application:
    name: emovie
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #写云数据库---------------------------------------------------------------
    url: jdbc:mysql://121.4.113.134:3306/emovie?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: shiwo2002625

  redis:
    host: 8.130.92.141
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决swagger和springboot冲突问题
  elasticsearch:
    uris: http://8.130.92.141:9200


logging:
  level:
    com.emovie: debug

#mybatis-plus:
#  type-aliases-package: com.emovie.entity # 别名扫描包

#-------------------JWT--------------------